'use client'
import '@/public/CSS/global.css'

import Navbar from '@/components/Navbar'

import { createContext, useState, useEffect } from 'react'
import { isAuth } from '@/utils/auth'
import { usePathname } from 'next/navigation'





export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export const MyContext = createContext();




export default function RootLayout({ children }) {
  const [login, setLogin] = useState(false);


  useEffect(() => {
    const fetchAuthStatus = async () => {
      setLogin(await isAuth())
    };
    console.log(login)
    fetchAuthStatus();
  }, []);

  const pathname = usePathname()
  const isDashboardPage = pathname.startsWith('/dashboard') ? true : false;

  return (
    <html lang="en">
      <body>
        <MyContext.Provider value={{ login, setLogin }}>
          <Navbar style={isDashboardPage ? 'none' : 'flex'} />
          {children}
        </MyContext.Provider>
      </body>
    </html>
  )
}
