import '@/public/CSS/global.css'

import Navbar from '@/components/Navbar'

//font awesome
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faGAmepad } from '@fortawesome/free-solid-svg-icons'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
