'use client'
import '@/public/CSS/global.css'

import Navbar from '@/components/Navbar'

import { createContext, useState } from 'react'
import { isAuth } from '@/utils/auth'
import { faColonSign } from '@fortawesome/free-solid-svg-icons'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export const MyContext = createContext();

async function checkToken() {
  const check = await isAuth()
  return check;
}

export default function RootLayout({ children }) {
  const [login, setLogin] = useState(checkToken());
  return (
    <html lang="en">
      <body>
        <MyContext.Provider value={{ login, setLogin }}>
          <Navbar />
          {children}
        </MyContext.Provider>
      </body>
    </html>
  )
}
